### ISSUE TITLE
Clicking anywhere in the upper half of the authorize page opens google sign-in dialog

### ISSUE THREAD

**Issue by tanmayrajani** [malipramod/google-photos-migration-app#1]
Clicking anywhere in the upper half of the authorize page (not just the buttons) opens google sign-in dialog.. which I thought is kinda weird. I haven't tried the app yet, but looks very handy. 

Thank you for making this :clinking_glasses:

**Comment by malipramod** [comment]
Fixed. conflicts between Google Login Button and Local CSS. Revamp the authorized page. 

Thank you!
